version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  circleci-oidc:
    parameters:
      aws_role_arn:
        type: string
        default: AWS_ROLE_ARN
    executor: cimg/aws:2022.06
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: ${<< parameters.aws_role_arn >>}
          aws-region: us-west-1
          profile-name: oidc
          role-session-name: deploy
          session-duration: 3600
      - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity
      - run:
          name: List S3 buckets
          command: aws s3 ls
      - run:
          name: List Elastic Container Registry (should fail, we did not grant permissions)
          command: aws ecr describe-repositories

workflows:
  main:
   jobs:
    - circleci-oidc:
       context:
        - just_oidc