version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  circleci-oidc:
    parameters:
      aws_role_arn:
        type: string
        default: AWS_ROLE_ARN
    executor: azure-cli/azure-docker
    steps:
      - run:
          name: Get short-term credentials
          command: |
            STS=($(aws sts assume-role-with-web-identity \
            --role-arn << parameters.aws_role_arn >> \
            --role-session-name "deploy" \
            --web-identity-token "${CIRCLE_OIDC_TOKEN}" \
            --duration-seconds 3600 \
            --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))
            echo "export AWS_ACCESS_KEY_ID=${STS[0]}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${STS[1]}" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=${STS[2]}" >> $BASH_ENV
      - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity

workflows:
  main:
   jobs:
    - circleci-oidc:
       context:
        - just_oidc